# app.py
import streamlit as st
from graph import compiled_squad

THREAD_CONFIG = {"configurable": {"thread_id": "dev_squad_session_1"}}

st.set_page_config(page_title="AI Dev Team", page_icon="💻", layout="wide")
st.title("💻 Autonomous Hierarchical Software Team Desk")
st.markdown("Powered by Groq & LangGraph State Feedback Loops")

# Left Sidebar: Inputs Workspace Panel
st.sidebar.header("📋 Product Backlog Ticket")
ticket_input = st.sidebar.text_area(
    "Describe the Feature Request:",
    value="Write a Python script that calculates the compound interest formula given a list of contributions dictionaries, stripping out data keys that are missing numerical balances.",
    height=150
)

if st.sidebar.button("Run Development Sprint", type="primary"):
    with st.spinner("Engineering Team actively collaborating..."):
        initial_payload = {
            "feature_request": ticket_input,
            "architecture_plan": "",
            "source_code": "",
            "review_feedback": "",
            "status": "initiated",
            "iterations": 0
        }
        # Clear/Reset baseline memory thread maps
        compiled_squad.update_state(THREAD_CONFIG, {"iterations": 0, "status": "initiated"}, as_node="planner")
        
        # Fire off autonomous execution flow to completion
        compiled_squad.invoke(initial_payload, THREAD_CONFIG)

st.divider()

# Fetch telemetry records out of storage thread snapshots
snapshot = compiled_squad.get_state(THREAD_CONFIG)

if snapshot.values:
    state_vals = snapshot.values
    current_status = state_vals.get("status", "")
    total_loops = state_vals.get("iterations", 0)
    
    # Render loop metrics alerts dynamically
    if current_status == "review_passed":
        st.success(f"🏆 SPRINT COMPLETED SUCCESSFULLY! Code cleared code review audits on iteration round #{total_loops}.")
    else:
        st.warning(f"⚠️ SPRINT COMPLETED WITH TERMINATION: Current code standing status is labeled: [{current_status.upper()}] after {total_loops} total rework efforts.")

    # Main Center UI Work Layout Canvas Tabs
    tab1, tab2, tab3 = st.tabs(["🏗️ Architecture Specifications", "🔍 QA Audit Log Reports", "📦 Final Source Code Output"])
    
    with tab1:
        st.subheader("Architectural Spec Maps (Generated by Planner Agent)")
        st.info(state_vals.get("architecture_plan", "No structural specifications found."))
        
    with tab2:
        st.subheader("Automated Quality Assessment Feedback (Generated by Reviewer Agent)")
        if state_vals.get("review_feedback"):
            st.code(state_vals.get("review_feedback"), language="text")
        else:
            st.write("No verification cycles logged yet.")
            
    with tab3:
        st.subheader("Target Executable Production Script Artifact (Generated by Coder Agent)")
        raw_code = state_vals.get("source_code", "")
        # Strip eventual accidental markdown wrappers if the model returned them anyway
        clean_code = raw_code.replace("```python", "").replace("```", "")
        st.code(clean_code, language="python")
else:
    st.info("System idle. Define an execution requirement task in the backlog side menu panel to awake worker sub-systems.")